USE FestFlow
GO

CREATE TABLE Feedback (
    ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    EventId UNIQUEIDENTIFIER NOT NULL,
    Rating INT,
    Feedback NVARCHAR(MAX) NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (EventId) REFERENCES Events(ID),
    FOREIGN KEY (UserId) REFERENCES Users(ID)
);
